# Generated by Django 5.2.1 on 2025-06-08 06:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.gamesession')),
            ],
            options={
                'unique_together': {('game_session', 'nickname')},
            },
        ),
    ]
