# Generated by Django 5.2.1 on 2025-06-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='password',
            new_name='pin',
        ),
    ]
