# Generated by Django 5.2.1 on 2025-06-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_password_player_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='host_nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
