# Generated by Django 5.2.1 on 2025-06-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamesession_host_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='option1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='option2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='option3',
            field=models.BooleanField(default=False),
        ),
    ]
