# Generated by Django 5.2.1 on 2025-06-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamesession_option1_gamesession_option2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
