# Generated by Django 5.2.1 on 2025-06-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamesession_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='player',
            name='role_detail',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='player',
            name='role_image',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='player',
            name='role_intro',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
