# Generated by Django 5.2.1 on 2025-06-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_role_player_role_detail_player_role_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role_detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='role_image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='role_intro',
            field=models.TextField(),
        ),
    ]
